# moonsbox config (TOML)
DEFAULT_TEMP = 300
TEMP_IS_EXCHANGING = true
DEFAULT_DRAWING_WIDTH = 1
DELTA_DRAWING_WIDTH = 1
ZOOM_FACTOR = 0.1
VOLUME = 1.0
MUSIC_VOLUME = 0.0
DRAWING_IS_CIRCULAR = true
DRAWING_IS_DESTRUCTIVE = false
WINDOW_CAPTION = "moonsbox"
SCREEN_SIZE = [560, 560]
MAP_SIZE = [100, 100]
VISIBLE_AREA = [-20, -20, 140, 140]
PALETTE_ICON_SIZE = [64, 64]
PALETTE_MAX_CAPTION_CHARS = 20
PALETTE_MARGIN = 20
MAP_INNER_COLOR = "#000000"
MAP_OUTER_COLOR = "#001A0B"
PALETTE_SELECTION_OUTER_COLOR = "#00C3FF40"
PALETTE_SELECTION_INNER_COLOR = "#008CFF20"
PALETTE_SHADOW_COLOR = "#000000CC"
FONT_SIZE = 15
FONT_NAME_OR_PATH = "Sans"
FONT_IS_SYSFONT = true
ENABLE_VSYNC = true
ENABLE_FPS_COUNTER = false
ENABLE_TPS_COUNTER = false
DEBUG_COLOR = "#00FF00"
USER_LOCALE = "auto"
ASSETS_ROOT = "./assets"
SCREENSHOT_PATH_FACTORY = "./screenshot_%Y-%m-%d_%H-%M-%S.png"
SCREENSHOT_TYPE_HINT = "PNG"
SCREENSHOT_DOT_SIZE = [1, 1]
CAPTURE_PATH_FACTORY = "./capture_%Y-%m-%d_%H-%M-%S/"
